name: Terraform action
on:
  push:
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]
    branches:
      - infraterra

permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
     
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -a

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5
      - name: Terraform Init
        id: init
        run: terraform init    
      - name: Terraform format
        run: terraform fmt -check
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply     
        run: terraform apply -auto-approve
      
